update

diff --git a/apps/x86_64-linux/installWithSecrets b/apps/x86_64-linux/installWithSecrets
--- a/apps/x86_64-linux/installWithSecrets
+++ b/apps/x86_64-linux/installWithSecrets
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -e
+set -exu
 
 check_installer() {
   if [ -e /etc/NIXOS ]; then
@@ -11,7 +11,7 @@ check_installer() {
 }
 
 cleanup() {
-  sudo rm -rf nixos-config-main.zip nixos-config-main nixos-config
+  rm -rf nixos-config-main.zip nixos-config-main nixos-config
 }
 
 download_config() {
@@ -22,12 +22,17 @@ download_config() {
 }
 
 run_apply() {
-  ./bin/apply
+  /mnt/etc/nixos/bin/apply
+  if [ ! -f /tmp/username.txt ]; then
+    echo -e "\e[1;31mError: /tmp/username.txt does not exist.\e[0m"
+    exit 1
+  fi
+  export USERNAME=$(cat /tmp/username.txt)
 }
 
 run_disko() {
   sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
-    github:nix-community/disko -- --mode zap_create_mount ./nixos-config/nixos/disk-config.nix
+    github:nix-community/disko -- --mode zap_create_mount ./nixos/disk-config.nix
 }
 
 setup_files() {
@@ -35,28 +40,43 @@ setup_files() {
   sudo cp -r * /mnt/etc/nixos
   cd /mnt/etc/nixos
 
-  sudo mkdir -p /root/.ssh
-  sudo touch /root/.ssh/known_hosts
-  sudo ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts
+  mkdir -p /root/.ssh
+  touch /root/.ssh/known_hosts
+  ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts
 }
 
 setup_ssh_keys() {
-  mkdir -p /mnt/home/${user}/.ssh
-  chown nixos /mnt/home/${user}/.ssh
+  mkdir -p /mnt/home/${USERNAME}/.ssh
+  chown nixos /mnt/home/${USERNAME}/.ssh
 
   chown nixos /root/.ssh/id_ed25519_agenix{,.pub}
-  cp --preserve=all /root/.ssh/id_ed25519_agenix /mnt/home/${user}/.ssh/id_ed25519
-  cp --preserve=all /root/.ssh/id_ed25519_agenix.pub /mnt/home/${user}/.ssh/id_ed25519.pub
+  cp --preserve=all /root/.ssh/id_ed25519_agenix /mnt/home/${USERNAME}/.ssh/id_ed25519
+  cp --preserve=all /root/.ssh/id_ed25519_agenix.pub /mnt/home/${USERNAME}/.ssh/id_ed25519.pub
 
-  chmod 600 /mnt/home/${user}/.ssh/id_ed25519{,.pub}
+  chmod 600 /mnt/home/${USERNAME}/.ssh/id_ed25519{,.pub}
 }
 
 link_home_dir() {
-  ln -s /mnt/home/${user} /home/${user} # Used to grab initial secrets
+  ln -s /mnt/home/${USERNAME} /home/${USERNAME} # Used to grab initial secrets
 }
 
 install_nixos() {
-  sudo nixos-install --flake .#nixos
+  ARCH=$(uname -m)
+
+  case "$ARCH" in
+    x86_64)
+      FLAKE_TARGET="x86_64-linux"
+      ;;
+    aarch64)
+      FLAKE_TARGET="aarch64-linux"
+      ;;
+    *)
+      echo -e "${RED}Unsupported architecture: $ARCH${CLEAR}"
+      exit 1
+      ;;
+  esac
+
+  sudo nixos-install --flake .#$FLAKE_TARGET $@
   sudo chmod -R 775 /mnt/etc/nixos
 }
 
@@ -68,6 +88,7 @@ prompt_reboot() {
   esac
 }
 
+cleanup
 check_installer
 download_config
 run_disko
